UPDATE YAO_PROPERTY SET VALUE = '2.2.3' WHERE NAME = 'schema.version';
CREATE TABLE YAO_RESOURCE (
    ID IDENTITY PRIMARY KEY,
    RESOURCE_ID VARCHAR(64),
    RESOURCE_NAME VARCHAR(64)
);
INSERT INTO YAO_RESOURCE VALUES (1, 'simulator', 'Simulator');
CREATE TABLE YAO_PROCESS (
    ID IDENTITY PRIMARY KEY,
    DEF_ID VARCHAR(64),
    DEF_NAME VARCHAR(255),
    PROCESS_ID VARCHAR(64),
    PROCESS_NAME VARCHAR(255),
    PROCESS_TYPE VARCHAR(8),
	IS_EXECUTABLE BOOLEAN,
	IS_CLOSED BOOLEAN,
    STATE TINYINT,
    VERSION INT,
    CREATE_TIME TIMESTAMP
);
CREATE TABLE YAO_PROCESS_INSTANCE (
    ID IDENTITY PRIMARY KEY,
    PROCESS_ID BIGINT,
    PROCESS_NAME VARCHAR(255),
    STATE VARCHAR(32),
    STATE_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP,
    FOREIGN KEY(PROCESS_ID) REFERENCES YAO_PROCESS(ID)
);
CREATE TABLE YAO_PROCESS_INSTANCE_DATA (
    ID IDENTITY PRIMARY KEY,
    PROCESS_INSTANCE_ID BIGINT,
    DATA_ID VARCHAR(64),
    DATA_NAME VARCHAR(64),
    DATA_TYPE VARCHAR(32),
    DATA_VALUE VARCHAR(255),
    FOREIGN KEY(PROCESS_INSTANCE_ID) REFERENCES YAO_PROCESS_INSTANCE(ID)
);
CREATE TABLE YAO_FLOW_NODE (
    ID IDENTITY PRIMARY KEY,
    PROCESS_INSTANCE_ID BIGINT,
    FLOW_NODE_ID VARCHAR(64),
    FLOW_NODE_NAME VARCHAR(64),
    STATE VARCHAR(32),
    STATE_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP,
    FOREIGN KEY(PROCESS_INSTANCE_ID) REFERENCES YAO_PROCESS_INSTANCE(ID)
);
CREATE TABLE YAO_FLOW_NODE_DATA (
    ID IDENTITY PRIMARY KEY,
    PROCESS_INSTANCE_ID BIGINT,
    FLOW_NODE_ID BIGINT,
    DATA_ID VARCHAR(64),
    DATA_NAME VARCHAR(64),
    DATA_TYPE VARCHAR(32),
    DATA_VALUE VARCHAR(255),
    FOREIGN KEY(PROCESS_INSTANCE_ID) REFERENCES YAO_PROCESS_INSTANCE(ID),
    FOREIGN KEY(FLOW_NODE_ID) REFERENCES YAO_FLOW_NODE(ID)
);
CREATE TABLE YAO_ASSIGNMENT (
	ID IDENTITY PRIMARY KEY,
    PROCESS_INSTANCE_ID BIGINT,
	FLOW_NODE_ID BIGINT,
	ASSIGNMENT_ID VARCHAR(64),
	ASSIGNMENT_NAME VARCHAR(64),
	IS_ACCEPTED BOOLEAN,
    FOREIGN KEY(PROCESS_INSTANCE_ID) REFERENCES YAO_PROCESS_INSTANCE(ID),
	FOREIGN KEY(FLOW_NODE_ID) REFERENCES YAO_FLOW_NODE(ID)
);